FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel

RUN apt-get update && apt-get install git ca-certificates  -y
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN pip install -e .