FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

RUN apt-get update && apt-get install git ca-certificates  -y
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN pip install -e .
ENV WANDB_API_KEY=e8d24680a3708a131030ff9268996add924a526d

