model:
  decoder_name: fpn
  encoder_name: resnet18
  dataset_name: pascal_voc

data:
  dataset_path: /data/monza/audi_r8_lms_2016/imitation-learning-fastlaps
  dataset_name: pascal_voc
  batch_size: 32
  n_workers: 4

trainer:
  logger: 
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: segmentation
      name: fpn-resnet18
      log_model: True
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      find_unused_parameters: False
  accelerator: gpu
  devices: -1
  precision: 16-mixed
  max_epochs: 300
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  benchmark: True
  sync_batchnorm: True

lr_scheduler:
  monitor: loss/val
  mode: min
  factor: 0.1
  patience: 10
  min_lr: 0.0

optimizer:
  lr: 0.0001
  eps: 1.0e-4
  amsgrad: True
  weight_decay: 0.01


